# Generated by Django 4.1.5 on 2023-02-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_tags_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='companyName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='jobProfile',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='typeOfOffer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
